### PR TITLE
fix(cli): expose missing mr_default_target_self project attribute

### LINKED ISSUE #2360: Expose call to change the default MR target project on the CLI
## Description of the problem, including code/CLI snippet

Since [GitLab 13.11](https://gitlab.com/gitlab-org/gitlab/-/blob/v13.11.0-ee/doc/user/project/merge_requests/creating_merge_requests.md#new-merge-request-from-a-fork) it is possible to change the default target project for a merge request in a non-private forked project ([#58093](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/58093)) and documented in [v14.7](https://gitlab.com/gitlab-org/gitlab/-/blob/v14.7.0-ee/doc/api/projects.md#get-single-project) (look for `mr_default_target_self`).

I have not been able to find a way to do it with the CLI; but it works fine with:

```python
project = gl.projects.get(project_id)
project.mr_default_target_self = True
project.save()
```

## Expected Behavior

Be able to use the CLI to set the target; i.e.: `gitlab project update --merge-requests-default-target <self | upstream>` or `gitlab project update --merge-requests-default-target-self <true | false>`.

## Actual Behavior

Not available?

## Specifications

  - python-gitlab version: 3.11.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 14.10.5-ee and GitLab.com

### PR DESCRIPTION
**Pull request by romain-dartigues**
Expose `mr_default_target_self` to the CLI.

Example::

   gitlab project update --id 616 --mr-default-target-self 1

References:

* https://gitlab.com/gitlab-org/gitlab/-/merge_requests/58093
* https://gitlab.com/gitlab-org/gitlab/-/blob/v13.11.0-ee/doc/user/project/merge_requests/creating_merge_requests.md#new-merge-request-from-a-fork
* https://gitlab.com/gitlab-org/gitlab/-/blob/v14.7.0-ee/doc/api/projects.md#get-single-project

 Closes #2360

### CODE REVIEW

**Comment by romain-dartigues** [comment]
Unsure how to add tests in `tests/functional/cli/test_cli_projects.py`.

I tried to blindly add a test case for the CLI in `tests/functional/api/test_projects.py`, but am unsure if relevant.

**Comment by nejch** [comment]
@romain-dartigues thanks a lot for working on this already! Don't worry about tests, it's just an additional attribute so no need.

You'll just need to `git commit --amend` and `git push -f` according to our commit message convention otherwise CI fails, as we use it for our changelogs. For example like this:

`fix(cli): expose missing mr_default_target_self project attribute`

**Comment by romain-dartigues** [comment]
Done, it's too easy. I have much to learn from your code, tests suites and all.
Thank you for this piece of software.

**Review by nejch — APPROVED** [review]
Thanks again @romain-dartigues! Yeah, we need to add some dev docs to make that first step a bit easier ;) Feel free to add more missing things if you stumble across anything else, now you should have a smoother experience going forward.

**Pull request merged**
