### PR TITLE
README.rst: fix the upstream Docker image reference

### PR DESCRIPTION
**Pull request by vvv**
v1.8.0 is not available.
```
Unable to find image 'registry.gitlab.com/python-gitlab/python-gitlab:v1.8.0' locally
docker: Error response from daemon: manifest for registry.gitlab.com/python-gitlab/python-gitlab:v1.8.0 not found: manifest unknown: manifest unknown.
```

### CODE REVIEW

**Comment by max-wittig** [comment]
Thanks for the MR. I would go for `latest`

**Comment by vvv** [comment]
> I would go for `latest`

Done.

**Comment by max-wittig** [comment]
@vvv Pipeline still fails, because the scope needs to be lowercase. Would you mind to adapt it to 

> docs(readme): fix docker image reference

Thanks 👍

**Comment by vvv** [comment]
> We enforce commit messages to be formatted using the [conventional-changelog](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines). This leads to more readable messages that are easy to follow when looking through the project history.

This also keeps the barrier to entry for new contributors unnecessarily high.

<a href="https://kottke.org/12/06/the-worlds-worst-password-requirements-list">password requirements</a>

**Comment by max-wittig** [comment]
But makes changelog generation easier ;) and you did it :D

**Pull request merged**
