### PR TITLE
add get artifact by ref and job

### LINKED ISSUE #818: ref based artifact download
## Description of the problem, including code/CLI snippet
Add support for downloading a single artifact based on branch name

https://docs.gitlab.com/ce/api/jobs.html#download-a-single-artifact-file-from-specific-tag-or-branch

## Specifications

  - python-gitlab version: 1.9.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.0.0

### PR DESCRIPTION
**Pull request by jgroom33**
Resolve #818

### CODE REVIEW

**Comment by max-wittig** [comment]
Thanks for your contribution. Would you mind to add some documentation about this feature?

**Comment by max-wittig** [comment]
Awesome :+1:. Could you also squash your commits and change the commit message according to our docs or shall I take over?

Something like:
```
feat: add job artifacts api
```

**Comment by jgroom33** [comment]
i don't mind if you squash it.  thanks!

**Comment by max-wittig** [comment]
Merged into master

**Pull request closed without merging**
