### PR TITLE
feat(api): implement a count method

### PR DESCRIPTION
**Pull request by Shkurupii**
Hi, I found an issue https://github.com/python-gitlab/python-gitlab/issues/682 which I think I can finish. At the moment work is in progress. I have added tests for http_head(), count(), gl.projects.count() and others.
@nejch, does my change make sense or what else needs to be done except docs? Documentation part is still on me.
Br, Alex

### CODE REVIEW

**Review by nejch — CHANGES_REQUESTED** [review]
Thanks for this @Shkurupii, looks great already!

The `count()` method comes with one big caveat. It relies on the `x-total` header which is not available with keyset pagination, and in some cases might not be returned at all on gitlab.com I believe, as they have a custom proxy setup. Have you tried this on any endpoints at gitlab.com?

So this should be clearly documented when you add the docs. And I think we should handle the KeyError people will get if it's not present with a more informative error message (maybe raise GitLabCountError as well). See https://gitlab.com/gitlab-org/gitlab/-/merge_requests/34273 for more discussion on this.

**Comment by max-wittig** [comment]
There is no need for this. We already have this functionality, when using a generator. 

See: https://python-gitlab.readthedocs.io/en/stable/api-usage.html#pagination

Please also keep in mind that GitLab will no longer send these `X-Something` headers in the future!

**Comment by Shkurupii** [comment]
Thanks. Now I see. Maybe that explains why https://github.com/python-gitlab/python-gitlab/issues/682 is stuck. The reason why I chose it is another issue https://github.com/python-gitlab/python-gitlab/issues/1447 where @nejch mentioned https://github.com/python-gitlab/python-gitlab/issues/682. I was thinking it's a good idea to bring http_head method to master from the first citation.
PR then can be closed, isn't? I will open new one just for https://github.com/python-gitlab/python-gitlab/issues/1447. What would you suggest?

**Comment by nejch** [comment]
Damn totally missed that we have this already. :facepalm:  https://github.com/python-gitlab/python-gitlab/blob/ce0e6427d448dfc18085a5403c793d9208ac3cf2/gitlab/client.py#L861

But yes my reference was to the HEAD request for people who don't want to fetch (presumably large) files just to see if they exist. So yes maybe open a PR just for that @Shkurupii based on the work here, thanks!

**Pull request closed without merging**
