### PR TITLE
change path for set_approvers to new api, with defaulted rule_type an…

### PR DESCRIPTION
**Pull request by charlesfayal**
…d added args for approvals_required

### CODE REVIEW

**Comment by max-wittig** [comment]
@charlesfayal Thanks for the MR! Could you please also update the documentation and the tests?

**Comment by charlesfayal** [comment]
@max-wittig how's that?

**Comment by charlesfayal** [comment]
@max-wittig Im a little confused how to test this manually. How can I build the python projection into an importable project to test in my own project?

**Comment by max-wittig** [comment]
@charlesfayal You can just install the wheel with pip `pip3 install python-gitlab.whl` or directly install it with `python3 setup install`

**Comment by max-wittig** [comment]
@charlesfayal Just report back, when I should take a look

**Comment by max-wittig** [comment]
@charlesfayal Thanks for the MR!

**Pull request merged**
