### PR TITLE
chore(dist): add test data

### LINKED ISSUE #907: 1.12.1 pypi dist file doesn't include gitlab/tests/json.data
FreeBSD ports system uses the distfile from pypi.  When running test on python-gitlab with the dist file from pypi it appears gitlab/tests/json.data isn't included. 

```
...
test_todo (gitlab.tests.test_gitlab.TestGitlab) ... ERROR 
...
======================================================================                                                                                                                                      
ERROR: test_todo (gitlab.tests.test_gitlab.TestGitlab)                                                                                                                                                      
----------------------------------------------------------------------                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                          
  File "/wrkdirs/usr/ports/devel/py-python-gitlab/work-py36/python-gitlab-1.12.1/gitlab/tests/test_gitlab.py", line 676, in test_todo                                                                       
    todo_content = open(os.path.dirname(__file__) + "/data/todo.json", "r").read()                                                                                                                          
FileNotFoundError: [Errno 2] No such file or directory: '/wrkdirs/usr/ports/devel/py-python-gitlab/work-py36/python-gitlab-1.12.1/gitlab/tests/data/todo.json'
Ran 103 tests in 0.510s                                                                                                                                                                                     
                                                                                                                                                                                                            
FAILED (errors=1)                                                                                                                                                                                           
Test failed: <unittest.runner.TextTestResult run=103 errors=1 failures=0>                                                                                                                                   
error: Test failed: <unittest.runner.TextTestResult run=103 errors=1 failures=0>                                                                                                                            
*** Error code 1                                                                                                                                                                                           
```


Manually placing the file allows all tests to pass.

### PR DESCRIPTION
**Pull request by bufferoverflow**
Closes #907

### CODE REVIEW

**Comment by max-wittig** [comment]
Did you test this? I think we are already in the gitlab dir.

**Comment by bufferoverflow** [comment]
```
$ python3 setup.py sdist bdist_wheel
$ tar -tvzf dist/python-gitlab-1.12.1.tar.gz | grep json
-rw-r--r--  0 meierro staff    2615 Oct 17 11:05 python-gitlab-1.12.1/gitlab/tests/data/todo.json
```

**Comment by bufferoverflow** [comment]
@max-wittig I just figured out that the file is not within `whl` and `egg` file, I'm unsure if it should be there or not.

**Comment by max-wittig** [comment]
@bufferoverflow Thanks for the MR!

**Pull request merged**
