### PR TITLE
refactor: format everything black

### LINKED ISSUE #772: Switch to black for code formatting
Let's align the code style of this project:

https://github.com/python/black

https://github.com/python/black#used-by

### PR DESCRIPTION
**Pull request by max-wittig**
Black seems to become the defacto standard for python formatting.

A lot of projects are using it already: https://github.com/python/black#used-by

Fixes #772

### CODE REVIEW

**Comment by max-wittig** [comment]
Yes. That's because of my merge in another merge request. See my revert of it. Then I need to rebase this.

**Comment by max-wittig** [comment]
https://github.com/python-gitlab/python-gitlab/pull/776

**Comment by max-wittig** [comment]
@gpocentek Pipeline passed now.

**Comment by gpocentek** [comment]
:+1:

**Pull request merged**
