### PR TITLE
chore: enforce python version requirements

### PR DESCRIPTION
**Pull request by max-wittig**

### CODE REVIEW

**Comment by bufferoverflow** [comment]
@max-wittig very nice! do you like wait until python 2 is gone?

**Comment by max-wittig** [comment]
Yes we will. I will craft a new release next year.

**Comment by max-wittig** [comment]
@bufferoverflow We already dropped support for 2 with the previous MR merged.

**Comment by max-wittig** [comment]
This is actually important, so that python2 users can still use the old version.

**Pull request merged**
