### PR TITLE
Support SSL verification via internal CA bundle

### PR DESCRIPTION
**Pull request by mdhausman**
- Also updates documentation
- See issues #204 and #270

### CODE REVIEW

**Comment by mdhausman** [comment]
Hm. It looks like all the failing checks are also failing on the current master branch. So the good news is, it's not by code breaking things. The bad news is, something is definitely broken.

**Comment by gpocentek** [comment]
The python3.6 failure is definitely not related to your patch. The functional tests failure is probably a temporary error. Let's see how it goes with a new run.

**Comment by gpocentek** [comment]
The patch looks good BTW, thanks!

**Comment by mdhausman** [comment]
Glad it looks good. Wish the tests were working, though 😅

**Comment by gpocentek** [comment]
Could you rebase your change on the current master? The tests should be OK now.

**Comment by mdhausman** [comment]
Success! 💃 🎉 🎊 🍾

**Comment by gpocentek** [comment]
Thank you!

**Pull request merged**
