### PR TITLE
wip: testing

### PR DESCRIPTION
**Pull request by JohnVillalovos**

### CODE REVIEW

**Comment by nejch** [comment]
Thanks @JohnVillalovos - should we turn this into a real PR to only get annotations from the coverage jobs (and functional)?

**Comment by JohnVillalovos** [comment]
> Thanks @JohnVillalovos - should we turn this into a real PR to only get annotations from the coverage jobs (and functional)?

If you want to take this over and use it to become a real PR, works for me. I guess could iterate on options with this failing test and then when finally ready remove the bad assert.

**Comment by nejch** [comment]
Sounds great! We can amend at the end.

**Comment by nejch** [comment]
@JohnVillalovos maybe I misunderstood here, should we close this PR or continue here?

**Comment by JohnVillalovos** [comment]
Let's just close this one

**Pull request closed without merging**
