### PR TITLE
added pipeline custom variables usage example

### PR DESCRIPTION
**Pull request by SVLay**
Add a little explanation, for the pipeline variables logic.

### CODE REVIEW

**Comment by max-wittig** [comment]
The change looks good to me. Could you please rebase to latest master and change our your commit message to match our contribution guidelines?

E.g. `docs(builds): add pipeline custom variables usage example`

**Comment by SVLay** [comment]
> The change looks good to me. Could you please rebase to latest master and change our your commit message to match our contribution guidelines?
> 
> E.g. `docs(builds): add pipeline custom variables usage example`

Sure, will do

**Comment by SVLay** [comment]
Created a new PR for that - https://github.com/python-gitlab/python-gitlab/pull/929

**Comment by max-wittig** [comment]
@SVLay Hint: You wouldn't need a new merge request. You can just amend the commit message and force push to your branch.

**Pull request closed without merging**
