### PR TITLE
feat(api): allow updating protected branches

### LINKED ISSUE #2390: Allow update of protected branches
In gitlab 15.6 gitlab finally added api support to update protected branch settings, so ProjectProtectedBranch should be updated accordingly

https://gitlab.com/gitlab-org/gitlab/-/issues/20229/

### PR DESCRIPTION
**Pull request by Sjord**
Closes #2390

## Changes

    p_b.allow_force_push = True
    p_b.save()

### Documentation and testing

Please consider whether this PR needs documentation and tests. **This is not required**, but highly appreciated:

- [x] Documentation in the matching [docs section](https://github.com/python-gitlab/python-gitlab/tree/main/docs)
- [x] [Unit tests](https://github.com/python-gitlab/python-gitlab/tree/main/tests/unit) and/or [functional tests](https://github.com/python-gitlab/python-gitlab/tree/main/tests/functional)

### CODE REVIEW

**Comment by Sjord** [comment]
I don't understand why the integration test fails. It works on my local instance, and the code seems to make sense:

```
p_b.allow_force_push = True
p_b.save()

p_b = project.protectedbranches.get("*-stable")
assert p_b.allow_force_push
```

**Comment by JohnVillalovos** [comment]
> I don't understand why the integration test fails. It works on my local instance, and the code seems to make sense:
> 
> ```
> p_b.allow_force_push = True
> p_b.save()
> 
> p_b = project.protectedbranches.get("*-stable")
> assert p_b.allow_force_push
> ```

Just a guess, but it may need to use the `wait_for_sidekiq()` function. As the GitLab server may still be processing the `save()` asynchronously while doing the `get()`.

`functional/api/test_merge_requests.py` has usage of `wait_for_sidekiq()`

**Comment by nejch** [comment]
Sadly our functional tests still run against 15.4 (yes, I know!) because we had issues with flaky and failing tests when upgrading. This was introduced in 15.6 so this is sort of expected. We need to take the time to fix that soon I guess.

I would suggest adding a skip or xfail (I forget if we still have a decorator for gitlab versions - that would be ideal. At least we have a `gitlab_version` fixture so you could conditionally test those few lines as well.

**Review by nejch — APPROVED** [review]
Thanks @Sjord and sorry for the delays! I'll go ahead and merge this now, but I'll squash the commits if that's ok with you as the other commits aren't user-facing fixes. Thanks again!

**Comment by nickbroon** [comment]
Is this expected to also work with `protectedbranch.allowed_to_merge` or `protectedbranch.merge_access_levels` ?

**Comment by Sjord** [comment]
I made this to support `allow_force_push`, and if anything else worked that would be a bonus. I expect `allowed_to_push` to work.

It is indeed a pain that the API expects different information than it returns. I have been bitten by this before, and I think I saw an issue about this in some other context, but I can't find it right now. Unfortunately, there is not really a clear solution for this.

Perhaps it's better to create a new issue for your problem. This pull request is already closed so comments here will get out of sight.

**Pull request merged**
