### PR TITLE
fix(objects): make resource access tokens and repos available in CLI

### PR DESCRIPTION
**Pull request by nejch**
This was a bit of an oversight from me a while ago and it's carried over to newer PRs.

### CODE REVIEW

**Review by JohnVillalovos — APPROVED** [review]
Thanks for catching this!

**Comment by JohnVillalovos** [comment]
So this looks good to me. Only thing would be nice a simple smoke test in the CLI to show that can call these now. Could be a `gitlab some_object --help`

**Comment by nejch** [comment]
> So this looks good to me. Only thing would be nice a simple smoke test in the CLI to show that can call these now. Could be a `gitlab some_object --help`

Just found out this won't work properly until we merge https://github.com/python-gitlab/python-gitlab/pull/1699 as scopes are required. So I'll add a proper test after that :)

**Comment by nejch** [comment]
> > So this looks good to me. Only thing would be nice a simple smoke test in the CLI to show that can call these now. Could be a `gitlab some_object --help`
> 
> Just found out this won't work properly until we merge #1699 as scopes are required. So I'll add a proper test after that :)

Actually, we can go ahead with at least the list endpoint for projects. Added some basic tests and when 14.7 is out we can enable more.

**Pull request merged**
