### PR TITLE
adds project upload feature

### PR DESCRIPTION
**Pull request by d0c-s4vage**
Needs unit tests still. see #56

### CODE REVIEW

**Comment by d0c-s4vage** [comment]
Attaching files to issues and issue notes seems to be working well though, now I'm trying to figure out the best way to do unit tests for this.

**Comment by gpocentek** [comment]
Cool addition :+1: 

I need a bit more time to test/digest the code. If you spend time on this I'd rather have functional tests to get examples of how to use the code (``tools/python_test.py``).

Thanks you!

**Comment by d0c-s4vage** [comment]
Totally! Wanted to push up the raw features while I figured out the unit
tests. I'll see if I can add some today.

**Comment by aruiz** [comment]
Any updates on this?

**Comment by gpocentek** [comment]
@aruiz Sorry but I didn't have enough time to properly review and test this patch. Hopefully things will get better soon.

**Comment by d0c-s4vage** [comment]
Is there anything else we need to do on this? Finally getting back to it

**Comment by gpocentek** [comment]
Hi @d0c-s4vage, sorry for not answering sooner.

I didn't take time to test an upload yet, but the code itself seems OK to me.

I'm not sure that python-gitlab should be responsible of adding the markdown in the issues/notes description. User will probably want to handle that part themselves (at the beginning, at the end, new note or existing one, ...). The Mixin class is probably not needed 

If you have time to implement this for v4 it would be great, but I can take care of it if you don't.

Thanks for adding this feature!

**Comment by d0c-s4vage** [comment]
@gpocentek ah, great point on that.  It's been a while since I've looked at my changes... I'll make the file upload/attachment a stand-alone feature that can return/generate markdown for the user.

**Comment by d0c-s4vage** [comment]
well crap, that rebase didn't work out how I thought it would

**Comment by d0c-s4vage** [comment]
Feature branch is now up-to-date with latest from python-gitlab/python-gitlab

**Comment by d0c-s4vage** [comment]
@gpocentek pending review/comments, I think this is done

**Comment by gpocentek** [comment]
Thanks for the update! I really appreciate the docs and tests! :)

It looks pretty good to me, I'm just wondering if the `InformationalObject` class is really useful. Making the `upload()` method return a simple dict (the Gitlab server data) seems good and simple enough to me. Maybe there's a useful goal I didn't catch there, but I believe in simple things ;)

**Comment by d0c-s4vage** [comment]
Hrmm, good point. I made the `InformationalObject` and the `ProjectUpload` classes so that the v4 cli result printing code would [work with fewer changes](https://github.com/python-gitlab/python-gitlab/pull/239/files#diff-e4c3e082d0590a80d9559f90fb59ab00R324). It would have been simpler to add a new case to print a `dict` I guess. I'll use that, remove the `InformationalObject` and `ProjectUpload` classes, and just return a `dict` from the `upload()` method.

Also, I don't know why the [build is failing on python2.7 cli_func_v4](https://travis-ci.org/python-gitlab/python-gitlab/jobs/267375797). I'll take another look and see if my code interfered with branch creation somehow:
image

**Comment by d0c-s4vage** [comment]
@gpocentek w00t! all tests are passing, I think this is good to go now.

**Comment by gpocentek** [comment]
Thank for your patience and the quality of this patch!

**Comment by d0c-s4vage** [comment]
Awesome! We're glad to contribute - we use python-gitlab pretty heavily

**Pull request merged**
