### PR TITLE
fix: use url-encoded ID in all paths (alternate method)

### PR DESCRIPTION
**Pull request by JohnVillalovos**
An alternative to https://github.com/python-gitlab/python-gitlab/pull/1819

Make sure all usage of the ID in the URL path is encoded. Normally it
isn't an issue as most IDs are integers or strings which don't contain
a slash ('/'). But when the ID is a string with a slash character it
will break things.

Add a test case that shows this fixes wikis issue with subpages which
use the slash character.

Closes: #1079

### CODE REVIEW

**Comment by JohnVillalovos** [comment]
I think this is cool 😎 

But I am thinking this is maybe a bit too magic. Also when things get json encoded they lose the url-encoding 😢

**Comment by JohnVillalovos** [comment]
The `EncodedId` class is kind of cool 😎 in my opinion... But also kind of complicated. It was really interesting figuring this out.

Interested to hear what you think @nejch

**Comment by nejch** [comment]
I guess we can close this one @JohnVillalovos as the changes were essentially incorporated into the original one right?

**Comment by JohnVillalovos** [comment]
> I guess we can close this one @JohnVillalovos as the changes were essentially incorporated into the original one right?

Yep!

**Pull request closed without merging**
