### PR TITLE
chore: revert compose upgrade

### PR DESCRIPTION
**Pull request by nejch**
Closes https://github.com/python-gitlab/python-gitlab/issues/2328
Closes https://github.com/python-gitlab/python-gitlab/issues/2330

### CODE REVIEW

**Comment by lmilbaum** [comment]
I invoked this PR on my RHEL 8 based laptop. It doesn't work because `podman compose` is broken. `podman` doesn't support the `compose` subcommand.

**Comment by nejch** [comment]
> I invoked this PR on my RHEL 8 based laptop. It doesn't work because `podman compose` is broken. `podman` doesn't support the `compose` subcommand.

Oh, it should continue looping and attempt `podman-compose` I thought. Although from what I can see that would fail if `podman` is not installed. Are you getting the same @JohnVillalovos?

I added both the `x compose` and `x-compose` variants as I assume most tools will become API-compatible with compose v2 at some point, so worth adding there.

**Comment by lmilbaum** [comment]
Got it. I had `docker-compose` installed in addition to `podman-compose`. Uninstalled `docker-compose`.

**Comment by lmilbaum** [comment]
```
E           Exception: Command podman-compose -f "/home/lmilbaum/repos/github.com/lmilbaum/python-gitlab/tests/functional/fixtures/docker-compose.yml" -p "pytest-python-gitlab" port gitlab 80 returned 2: """usage: podman-compose [-h] [-v] [-f file] [-p PROJECT_NAME]
E                                 [--podman-path PODMAN_PATH] [--podman-args args]
E                                 [--podman-pull-args args] [--podman-push-args args]
E                                 [--podman-build-args args] [--podman-inspect-args args]
E                                 [--podman-run-args args] [--podman-start-args args]
E                                 [--podman-stop-args args] [--podman-rm-args args]
E                                 [--podman-volume-args args] [--no-ansi] [--no-cleanup]
E                                 [--dry-run]
E                                 {help,version,pull,push,build,up,down,ps,run,exec,start,stop,restart,logs}
E                                 ...
E           podman-compose: error: argument command: invalid choice: 'port' (choose from 'help', 'version', 'pull', 'push', 'build', 'up', 'down', 'ps', 'run', 'exec', 'start', 'stop', 'restart', 'logs')
E           """.

.tox/api_func_v4/lib/python3.9/site-packages/pytest_docker/plugin.py:24: Exception
```

**Comment by lmilbaum** [comment]
Can we continue the discussion/troubleshooting over a chat?

**Comment by lmilbaum** [comment]
In any case, I almost sure that the `pytest-docker` plugin support only `docker-compose`.  The [CI](https://github.com/avast/pytest-docker/blob/master/.github/workflows/tests.yaml) check only `docker-compose`.

**Comment by nejch** [comment]
@lmilbaum ah sorry, I was out for a bit. Looks like `podman-compose` does not support the port subcommand that is used here to inspect the service ports, and I'm not sure if it will - https://github.com/containers/podman-compose/issues/276. I'll revert to the the old v1 docker-compose command here.

**Review by JohnVillalovos — APPROVED** [review]
Thanks!

**Pull request merged**
