### PR TITLE
Add support to resource milestone events

### LINKED ISSUE #1154: Add support for resource milestone events
Although resource label events are supported by `python-gitlab`, it seems that [resource milestone events](https://docs.gitlab.com/ce/api/resource_milestone_events.html) are not. These are useful for tracking when resources are added and removed from milestones, for example when creating burndown charts.

It's not totally clear to me how new object types can be added to the library, but if someone is willing to offer a bit of advice, I'd be happy to have a first go at adding this feature.

## Specifications

* python-gitlab version: 2.2.0
* API version you are using (v3/v4): v4

### PR DESCRIPTION
**Pull request by Shkurupii**
Closes #1154

### CODE REVIEW

**Comment by Shkurupii** [comment]
Bad commit message

**Comment by Shkurupii** [comment]
@max-wittig take a look, please!

**Comment by max-wittig** [comment]
Thanks for the MR. Could you just please add some tests to it? 👍

**Comment by Shkurupii** [comment]
What kind of tests? Please, elaborate. I am using "resourcelabelevents" for a starting point, so I have added to python_test_v4.py another two tests for milestones as same as for the resourcelabelevents.

**Comment by max-wittig** [comment]
You've added functional tests. Would you mind to also add some unittests here? https://github.com/python-gitlab/python-gitlab/tree/master/gitlab/tests/objects

**Comment by Shkurupii** [comment]
@max-wittig Hi, check this out. Also, I can't understand why black fails my changes. WDYT? Please, advise.

**Comment by Shkurupii** [comment]
> @max-wittig Hi, check this out. Also, I can't understand why black fails my changes. WDYT? Please, advise.

Found out that Travis black is a higher version than mine. Add another commit to make linter happy.

**Review by max-wittig — APPROVED** [review]
I'm sorry for the black breakage. I guess it makes sense to pin the version.

Thanks for the MR!

**Pull request merged**
