### PR TITLE
ci: prevent merge-commits in a PR

### PR DESCRIPTION
**Pull request by JohnVillalovos**
Have the CI prevent merge-commits being part of a PR

### CODE REVIEW

**Comment by JohnVillalovos** [comment]
Goal of this is to block PRs like: https://github.com/python-gitlab/python-gitlab/pull/2780

**Comment by JohnVillalovos** [comment]
This should not be required as we have "Prevent Linear History" set in the settings for the protected branch `main`

**Comment by nejch** [comment]
Thanks @JohnVillalovos that was my thinking as well. I guess that was merged before we enabled the feature right?

**Comment by JohnVillalovos** [comment]
> Thanks @JohnVillalovos that was my thinking as well. I guess that was merged before we enabled the feature right?

I guess so. There is no history (that I know of) where we can see when settings where changed for the project on GitHub.

**Pull request closed without merging**
