### PR TITLE
feat: add audit endpoint

### PR DESCRIPTION
**Pull request by idanbensha**
Added audit events feature used for gitlab EE.
As requested in this issue:
https://github.com/python-gitlab/python-gitlab/issues/948

This code was tested and is working properly.

### CODE REVIEW

**Comment by max-wittig** [comment]
@idanbensha Thanks for this contribution! Would you mind to format your commit message, according to the conventions in this repo?

For example: `feat: add audit endpoint`

**Comment by idanbensha** [comment]
@max-wittig Sure, it's done, thanks :)

**Comment by max-wittig** [comment]
@idanbensha Pipeline still fails, because your other commit is still in there.

Could you squash your commits into one?

**Comment by idanbensha** [comment]
@max-wittig Done :) Pipeline passes.

**Pull request merged**
