### PR TITLE
Add support for query ldap groups links

### PR DESCRIPTION
**Pull request by andrewlarssen**
You can currently add or delete ldap links but you can't query existing links

### CODE REVIEW

**Comment by andrewlarssen** [comment]
For issue https://github.com/python-gitlab/python-gitlab/issues/1609

**Comment by andrewlarssen** [comment]
Have tested this manually on a real gitlab instance. I could not see any automated tests for gitlab -> ldap features

**Comment by andrewlarssen** [comment]
Fixed 2 linting issues. One was commit message so had to force push

**Review by nejch — CHANGES_REQUESTED** [review]
Thanks a lot @andrewlarssen! Just a comment on naming consistency. If you're able to add some unit tests to this, would also be great! Here https://github.com/python-gitlab/python-gitlab/blob/master/tests/unit/objects/test_groups.py or you could create a new `test_ldap_links.py` if it's getting too crowded there. Unit tests mock the responses so we can test EE features there.

While reviewing this I noticed our existing method for deletion uses deprecated API endpoints: https://docs.gitlab.com/ee/api/groups.html#delete-ldap-group-link

So as a bonus if you find time, I think these methods actually could be removed and you can add the CreateMixin/DeleteMixin to the manager, and ObjectDeleteMixin to the object. Then we could remove the custom methods here:

https://github.com/python-gitlab/python-gitlab/blob/227607ca47c78e3958c6649edb644c7e26d55281/gitlab/v4/objects/groups.py#L112-L150)

This would be a breaking change, but we have a major release coming up anyway. Let me know if this makes sense or you need help. Also, you'll just need to amend your message again as commitlint does not like capitalized sentences :)

**Pull request closed without merging**
