### PR TITLE
docs(commits): fix commit create example for binary content

### PR DESCRIPTION
**Pull request by tschm**
little problem in the documentation

### CODE REVIEW

**Comment by lmilbaum** [comment]
Please note that a merge commit pulled into the PR. Is that by intention?

**Comment by tschm** [comment]
No, please ignore the second commit. It's only the first commit I am after.

**Comment by lmilbaum** [comment]
> No, please ignore the second commit. It's only the first commit I am after.

All the commits of the PR are merged as soon as the PR is merged. There is no way, AFAIK, to cherry pick PR commits.

**Comment by nejch** [comment]
Thanks for the contribution @tschm!

We can squash on merge, but it would be great if you could squash/edit your commit message to match our commit message guidelines, so it shows up in the changelog as a Docs entry. See https://www.conventionalcommits.org/en/v1.0.0/#summary for more examples :)

**Comment by tschm** [comment]
I think, I could try a new PR from scratch next Tuesday if the problem is still open by then...

**Comment by nejch** [comment]
@tschm I rebased this branch on GitHub so it just has your commit. You'll just need to do a `git commit --amend` though, and use conventional commit messages so CI passes. let us know if you need help :)

**Comment by tschm** [comment]
Please delete this pull request but please fix the little glitch in the documentation. I will try again next time...

**Comment by nejch** [comment]
@tschm I have force-pushed to your branch to fix the commit message and keep you as author. Thanks for the contribution!

**Review by nejch — APPROVED** [review]

**Comment by lmilbaum** [comment]
@tschm,  do you need some guidance on Github workflow?  I am doing a lot of knowledge sharing sessions on this topic and others on my spere time. Feel free to reach out.

**Comment by lmilbaum** [comment]
@nejch Are you aware if a unit or/and functional test exists which catches this issue? If there is one then providing a link to the test can provide additional clarity.

**Comment by nejch** [comment]
> @nejch Are you aware if a unit or/and functional test exists which catches this issue? If there is one then providing a link to the test can provide additional clarity.

I checked and we don't have one specifically for this (binary content uploads on commit creation). I considered adding something for future reference, but decided to just trust @tschm's contribution for now instead :grin: but this might be useful!

**Comment by lmilbaum** [comment]
> > @nejch Are you aware if a unit or/and functional test exists which catches this issue? If there is one then providing a link to the test can provide additional clarity.
> 
> I checked and we don't have one specifically for this (binary content uploads on commit creation). I considered adding something for future reference, but decided to just trust @tschm's contribution for now instead 😁 but this might be useful!

@nejch Thanks for checking. Maybe, @tschm would like to contribute the test impplementation in a followup PR.

**Comment by tschm** [comment]
> @tschm, do you need some guidance on Github workflow? I am doing a lot of knowledge sharing sessions on this topic and others on my spare time. Feel free to reach out.

These days I am mainly active on Gitlab where we are running merge requests. If you have a document explaining some of those differences I would def read it. I understand my problem was that I merged my change back into my main(?!) and that I wasn't following the standard template for my commit. I am guilty.

**Pull request merged**
