### PR TITLE
chore: bump version to 2.7.0

### PR DESCRIPTION
**Pull request by max-wittig**
@nejch I think it's time again to release. It's been a while

### CODE REVIEW

**Comment by JohnVillalovos** [comment]
Cool! I like a new release 😊

**Review by JohnVillalovos — APPROVED** [review]

**Comment by nejch** [comment]
Yay, agreed! :smile_cat: 

I'd just like to fix one small thing before this goes out, when I added https://github.com/python-gitlab/python-gitlab/pull/1363 the deprecationwarning was too eager and on master now everyone gets it when `Gitlab` is instantiated:

```python
>>> gl = Gitlab.from_config()
/home/nejc/repos/python-gitlab/gitlab/v4/objects/audit_events.py:70: DeprecationWarning: This class has been renamed to ProjectAuditEvent and will be removed in a future release.
  class ProjectAudit(ProjectAuditEvent):
/home/nejc/repos/python-gitlab/gitlab/v4/objects/audit_events.py:74: DeprecationWarning: This class has been renamed to ProjectAuditEventManager and will be removed in a future release.
  class ProjectAuditManager(ProjectAuditEventManager):
```

@max-wittig could you merge https://github.com/python-gitlab/python-gitlab/pull/1414 and then this is ready? :)

**Comment by max-wittig** [comment]
Thinking about it, this version should anyway be called **3.0.0**, as we introduced some breaking changes with the way kwargs are used.

**Comment by nejch** [comment]
> Thinking about it, this version should anyway be called **3.0.0**, as we introduced some breaking changes with the way kwargs are used.

Oh, you mean https://github.com/python-gitlab/python-gitlab/pull/1278? That's not merged yet :blush: 

I was hoping to finish https://github.com/python-gitlab/python-gitlab/pull/1296 for 3.0.0 as that would be a very popular feature IMO but might also have some breaking behavior.

**Comment by max-wittig** [comment]
Makes sense. I merged it. Let's go for 2.7.0 then 👍

**Pull request merged**
