### PR TITLE
refactor: migrating timeout from client to http_backend

### PR DESCRIPTION
**Pull request by lmilbaum**
@nejch The PR is ready for review but I'm not sure the functional tests cover this change. LMK if you think that adding functional tests might be of help.

### CODE REVIEW

**Comment by nejch** [comment]
Thanks a lot for the PR @lmilbaum! Could you give me a bit of context on why this change is necessary? As it's just an `int`, I don't see from this PR how this would be dependent on a specific backend implementation. I'd assume we can just pass it on to the backend(s) as well as the custom methods (as in `projects.py`), and keep a minimum of changes to the `Gitlab` client itself.

Just asking as I think we need to keep breaking changes to a minimum. We are already introducing a slight breaking behavior with our `session` migration (though I think that's much more backend-specific and needed).

**Comment by lmilbaum** [comment]
> Thanks a lot for the PR @lmilbaum! Could you give me a bit of context on why this change is necessary? As it's just a `float`, I don't see from this PR how this would be dependent on a specific backend implementation. I'd assume we can just pass it on to the backend(s) as well as the custom methods (as in `projects.py`), and keep a minimum of changes to the `Gitlab` client itself.
> 
> Just asking as I think we need to keep breaking changes to a minimum. We are already introducing a slight breaking behavior with our `session` migration (though I think that's much more backend-specific and needed).

What makes sense to me is to wrap all the related business logic by the http backend. `timeout` is part of the related business logic.
I can close the PR and move on to other functions if you find it risky.

**Comment by nejch** [comment]
> What makes sense to me is to wrap all the related business logic by the http backend. `timeout` is part of the related business logic. I can close the PR and move on to other functions if you find it risky.

I may be wrong here but there will always be some things relevant to the client itself and likely even across different clients in the future (REST/GraphQL): base URL, auth params, SSL verify, retry params, timeout, user agent etc (of course backends may process these differently internally depending on implementation). And we can also see with the custom `import_*` methods that reuse it outside of backend code, it may be useful like that sometimes.

By keeping these as explicit arguments in the public interface, IMO we are also helping the end user as it's very clear in type hints, IDE auto-completion and in auto-generated docs.

**Comment by lmilbaum** [comment]
> > What makes sense to me is to wrap all the related business logic by the http backend. `timeout` is part of the related business logic. I can close the PR and move on to other functions if you find it risky.
> 
> I may be wrong here but there will always be some things relevant to the client itself and likely even across different clients in the future (REST/GraphQL): base URL, auth params, SSL verify, retry params, timeout, user agent etc (of course backends may process these differently internally depending on implementation). And we can also see with the custom `import_*` methods that reuse it outside of backend code, it may be useful like that sometimes.
> 
> By keeping these as explicit arguments in the public interface, IMO we are also helping the end user as it's very clear in type hints, IDE auto-completion and in auto-generated docs.

Makes sense. Closing the PR.

**Pull request closed without merging**
