### PR TITLE
Fix doc typo

### PR DESCRIPTION
**Pull request by bmwiedemann**

### CODE REVIEW

**Comment by max-wittig** [comment]
Thanks for this MR. Would you mind to format your commit message in the conventional changelog format?

**Comment by bmwiedemann** [comment]
like this?

**Comment by max-wittig** [comment]
@bmwiedemann Yes. Perfect. Thanks!

**Comment by max-wittig** [comment]
@bmwiedemann Yes. Perfect. Thanks!

**Pull request merged**
