### PR TITLE
Also retry HTTP-based transient errors

### PR DESCRIPTION
**Pull request by mitar**
So currently the library can automatically retry when there are some types of API errors. But sometimes the HTTP calls fails on a lower level (connection broken, etc.). I think that should count as a transient error as well and be retried if configured so. This PR adds this.

Closes https://github.com/python-gitlab/python-gitlab/issues/1885

### CODE REVIEW

**Comment by nejch** [comment]
Thanks for this @mitar. As this grows (I believe you also added the initial retry flag?), I'm wondering if we should switch to using the https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#urllib3.util.Retry utility for this. It might reduce our duplication and even clean up our custom 429 handling.

Would you like to give it a try here? If not we can do this in a follow-up, but it'd be great if we could at least have tests for this so that we can see it still behaves properly later. One example of similar tests is here, I think:
https://github.com/python-gitlab/python-gitlab/blob/master/tests/unit/test_gitlab_http_methods.py#L58-L123

**Comment by mitar** [comment]
Unstale.

**Comment by nejch** [comment]
@mitar did you still want to take a look at urllib3's retry class or you want to proceed this way?

**Comment by nejch** [comment]
@mitar as we're getting more requests on this I'm happy to merge this as is and we can work on the rest later, could you just rebase/resolve conflicts please? :bow:

**Comment by Sineaggi** [comment]
@mitar Would you mind if someone else took over this pr?

**Comment by mitar** [comment]
Hey, sorry, I got busy with other things. I can add anyone to the branch if you wan to rebase/fix conflicts. I will try to do it as well, but I do not know when I will be able to circle back to this.

**Comment by mitar** [comment]
(But definitely sadly I do not have time to add more tests or to port it to urlib3. I would suggest that this gets merged and then followup work is done to get things further. Also, I have been running this code for some time now and it works great/stable.)

**Comment by Sineaggi** [comment]
I've rebased @mitar's branch here https://github.com/python-gitlab/python-gitlab/pull/1904

Added tests and 52x http response range to retries.

**Comment by nejch** [comment]
Closing this in favor of https://github.com/python-gitlab/python-gitlab/pull/1904, as I see git commit authorship was preserved. Thanks for the work here @mitar.

**Pull request closed without merging**
