### PR TITLE
fix: extend wait timeout for test_delete_user()

### PR DESCRIPTION
**Pull request by JohnVillalovos**

### CODE REVIEW

**Comment by nejch** [comment]
Thanks for looking into this one. TBH I'm not sure anymore if the sidekiq metrics are a reliable source for the slow async operations - the point was to avoid hardcoded sleeps due to the underpowered CI VMs. I haven't taken the time to investigate it, so if you can solve it that's great, but don't lose too much time over this :)

**Comment by JohnVillalovos** [comment]
> 
> 
> Thanks for looking into this one. TBH I'm not sure anymore if the sidekiq metrics are a reliable source for the slow async operations - the point was to avoid hardcoded sleeps due to the underpowered CI VMs. I haven't taken the time to investigate it, so if you can solve it that's great, but don't lose too much time over this :)

Thanks. Doing some debugging at the moment. I'll see what I figure out.

**Comment by JohnVillalovos** [comment]
Not sure if this fixes the issue. Especially if the sidekick operations can not be counted on. 

But it should not hurt.

**Comment by nejch** [comment]
> Not sure if this fixes the issue. Especially if the sidekick operations can not be counted on.
> 
> But it should not hurt.

Cool, I guess the only thing that might happen is that some rogue sidekiq processes will drag this longer, but this was probably already the case and I forget what I was trying to achieve with relying only on the first process :grin:

**Pull request merged**
