### PR TITLE
chore: release tags to PyPI automatically

### LINKED ISSUE #609: Automatically publish to PyPI, when new tag is created
This would simplify the deployment process for you @gpocentek 
From the [travis documentation](https://docs.travis-ci.com/user/deployment/pypi/)
```txt
travis encrypt your-password-here --add deploy.password
```

```yaml
deploy:
  provider: pypi
  user: "Your username"
  password:
    secure: "Your encrypted password"
```

### PR DESCRIPTION
**Pull request by max-wittig**
Fixes #609

### CODE REVIEW

**Comment by gpocentek** [comment]
Cool :)

Would it make sense to create a dedicated user on pypi for this? If something goes wrong all your projects on pypi will be impacted.

**Comment by gpocentek** [comment]
I'm just trying to consider all the possible problems that could happen.

I don't know how we could handle a "bot user" easily. Any idea on how we should do that?

**Comment by max-wittig** [comment]
It's difficult as we can't handle the secret together. We have no encrypted channel. I guess it would be best, if you would handle the secret for the bot user, as original creator/maintainer.

**Comment by max-wittig** [comment]
@gpocentek Feel free to insert your own/bot-secret secret on this branch.

Use the travis-cli to encrypt it

```bash
docker run -v $(pwd):/project --rm skandyla/travis-cli encrypt <your-pypi-passwd> --add deploy.password -r python-gitlab/python-gitlab
```

**Comment by max-wittig** [comment]
@gpocentek How are we gonna proceed here?

**Comment by gpocentek** [comment]
@max-wittig if that's still OK with you let's merge this, we can update the user later if we find a better solution.

**Comment by max-wittig** [comment]
Fine by me :+1

**Pull request merged**
