### PR TITLE
Simplify the example for streamed artifacts

### PR DESCRIPTION
**Pull request by tardyp**
Going through an object adds a lot of complication.
Adding example for unzipping on the fly

### CODE REVIEW

**Comment by tardyp** [comment]
restarting ci

**Comment by gpocentek** [comment]
Thanks again @tardyp  :)

Your example is clearly simpler, but I'd rather keep the class-based example as well, as a way to illustrate a bit more complex setups. Could you update your patch?

**Comment by tardyp** [comment]
@gpocentek here you go

**Comment by gpocentek** [comment]
@tardyp Thanks for the fast update! I'll let the CI do its job then merge.

**Pull request merged**
