### PR TITLE
feat: add share/unshare the group with a group

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by sathieu** [comment]
@max-wittig This is now ready. Please review.

**Comment by sathieu** [comment]
@max-wittig Please review. It also includes a commit to fix the CI.

**Comment by max-wittig** [comment]
Thanks for the MR. Looks good! We might need to revert the CI fix commit, as GitLab not recognised the issue: https://gitlab.com/gitlab-org/gitlab/-/issues/238165

**Comment by sathieu** [comment]
Thanks !

**Pull request merged**
