### PR TITLE
WIP: migrate to asyncio and httpx

### LINKED ISSUE #945: migrate to asyncio
## Description of the problem, including code/CLI snippet

all the requests done in this module are syncronous. to use it more efficiently all requests should be converted to https://aiohttp.readthedocs.io/en/stable/ to make them concurrent

## Expected Behavior

posibility for concurrent requests

## Actual Behavior

only syncronus requests

## Specifications

  - python-gitlab version:
  - API version you are using (v3/v4):
  - Gitlab server version (or gitlab.com):

### PR DESCRIPTION
**Pull request by L0ric0**
starting to migrate to async while staying compatible to the syncronous versions.

TODO:
* [x] rewrite GitlabList __init__ to be async compatible
* [ ] find all functions that need a async_ version 

which funktions are suposed to be called by the user? if possible i would like to keep all internal funktions async and run the functions that have to be sync with `run_until_complete()`

would it be better to have a centrel event_loop instead of getting it with `get_event_loop` every time and if so where would i put it?

fix #945

### CODE REVIEW

**Comment by L0ric0** [comment]
at the moment the httpx module dose not support `auth` in the `httpx.Request` object and doesn't supply a `client.prepare_request` method so that the `http_request` method in `__init__.py` doesn't work. Does somebody know of an alternative?

**Comment by max-wittig** [comment]
Thanks for all the efforts on this. Maybe we should wait until the 1.0 release of https in April?

> A 1.0 release is expected to be issued sometime on or before April 2020.`

**Comment by L0ric0** [comment]
yeah probably hopefully they fix the two issues that are blocking this pr

**Comment by Tadaboody** [comment]
Hello! I'm willing to help with getting this PR done to learn some more asyncio :) 

One question - why httpx? how does it compare to libraries like [aiohttp](https://docs.aiohttp.org/en/stable/)?

**Comment by darkdragon-001** [comment]
Can you check if [httpx version 1.0.0.beta0](https://github.com/encode/httpx/releases/tag/1.0.0.beta0) fixes the remaining issues?

**Comment by JohnVillalovos** [comment]
No activity in almost two years from the author. Closing.

**Pull request closed without merging**
