### PR TITLE
chore(deps): update mypy (1.0.0) and responses (0.22.0)

### PR DESCRIPTION
**Pull request by JohnVillalovos**
Update the `requirements-*` files.

In order to update mypy==1.0.0 we need to also update
responses==0.22.0

Fix one issue found by `mypy`

Leaving updates for `precommit` to be done in a separate commit by
someone.

### CODE REVIEW

**Comment by lmilbaum** [comment]
I wonder if renovate could picked this up

**Comment by JohnVillalovos** [comment]
> I wonder if renovate could picked this up

Yes it would. But I did it to show the mypy issue that is broken for us.

**Comment by JohnVillalovos** [comment]
@nejch I don't know why renovate didn't already propose a change to update `responses` which was released on 11-Oct-2022. Maybe you know?

**Comment by JohnVillalovos** [comment]
> > I wonder if renovate could picked this up
> 
> Yes it would. But I did it to show the mypy issue that is broken for us.

@lmilbaum Or maybe better to say "it should" update it. Based on `responses` not being updated I'm thinking something maybe wrong with renovate.

Last time renovate did an update to `requirements-lint.txt` is 6-Oct-2022 ☹️

**Comment by nejch** [comment]
Thanks @JohnVillalovos, I'll tackle the renovate issue separately as I see you already opened a follow-up :)

**Pull request merged**
