### PR TITLE
chore(ci): update latest docker image for every tag

### LINKED ISSUE #918: repositories.list() fails with hub.docker.com image
## Description of the problem, including code/CLI snippet
the current version of the docker image can not handle the function "repositories.list()".
If I update python-gitlab inside the container it works, so please update your hub.docker.com image :).

```bash
Traceback (most recent call last):
  File "/scripts/registry-cleaner-script.py", line 91, in <module>
    main()
  File "/scripts/registry-cleaner-script.py", line 87, in main
    delete_tags(git_nr, args.projectid, args.regexp, args.keep, args.time)
  File "/scripts/registry-cleaner-script.py", line 39, in delete_tags
    repositories = project.repositories.list()
  File "/usr/local/lib/python3.7/site-packages/gitlab/base.py", line 81, in __getattr__
    raise AttributeError(name)
AttributeError: repositories
```

## Expected Behavior
to list all repositories of a project

## Actual Behavior
throws an exception see code snippet

## Specifications

  - python-gitlab version: public hosted docker image : https://hub.docker.com/r/pythongitlab/python-gitlab/builds
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 12.3.5

### PR DESCRIPTION
**Pull request by max-wittig**
Fixes #918

### CODE REVIEW

**Comment by bufferoverflow** [comment]
No pipeline at https://gitlab.com/python-gitlab/python-gitlab yet

**Comment by max-wittig** [comment]
@bufferoverflow yes, because this only works for tags.

**Comment by bufferoverflow** [comment]
@max-wittig ok, so shall I merge?

**Comment by max-wittig** [comment]
@bufferoverflow yes

**Pull request merged**
